### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by moonboy12138** [MWieland/s1s2_water#3]
Thank you for this excellent work! Will the train and test code, along with the dataloader, be released? It would be very helpful for us to utilize the dataset!

**Comment by MWieland** [comment]
Dear @moonboy12138 thanks for raising this issue. We have accordingly just released the Sentinel-1 [SNAP preprocessing graph](https://github.com/MWieland/s1s2_water/blob/main/prepare/preproc_s1_snap.xml) to ensure reproducibility of the image preprocessing. We are, however, not planning to release the whole training and testing code.

**Comment by moonboy12138** [comment]
@MWieland Thanks for your patient reply. I noticed that the Sentinel-1 image and the Sentinel-2 image in the same folder do not have the same image size. If I want to use them for multimodal fusion purposes, how should I map them to ensure they align correctly in the same geo-location?
