### ISSUE TITLE
Question on s1 images pre-processing

### ISSUE THREAD

**Issue by laetitialalla** [MWieland/s1s2_water#4]
Hello, 

thank you very much for providing this very nice dataset ! I am sure there has been a tremendous amount of work behind this. 

I just have one question : I would like to use s1s2_water as a training dataset and apply the model to other images (like Copernicus freely avalable data), so I would like to know **what pre-processing steps you performed on your images**. Especially for the s1 images. 

In your paper you write "_The Sentinel-1 images are geometrically corrected and radiometrically calibrated according to the method described by Twele et al. [33]_." And [33] states « _After data pre-processing using the S1TBX, the calibrated data are ﬁltered to reduce SAR inherent speckle noise._ » Since there are many de-speckling filters implemented in the S1TBX (ESA Sentinel-1 toolbox), can I ask wich one you chose and with which parameters ? 

Thanks again for releasing this dataset which will allow great progress in water bodies detection ! 

All the best

**Comment by MWieland** [comment]
Dear @laetitialalla , thanks for raising this issue. We have just released the respective [SNAP preprocessing graph](https://github.com/MWieland/s1s2_water/blob/main/prepare/preproc_s1_snap.xml) that should include all the required details and enable the user to reproduce the Sentinel-1 preprocessed images.

**Comment by laetitialalla** [comment]
Great, thanks for your answer ! :)
