### ISSUE TITLE
Missing s1 images for scenes 31 and 59 

### ISSUE THREAD

**Issue by laetitialalla** [MWieland/s1s2_water#6]
Hello again !

I downloaded your dataset and, unless i'm mistaken, it seems that scenes 31 and 59 do not have the corresponding s1 images, s1 masks and s1 valid masks. 
Maybe you removed these 2 for a reason ? 
(but scene 31 was in your test set for sentinel1, so I guess at least this one has a matching s1 image :) ) 

Thanks a lot for your help ! 

Best regards, 
Laetitia

**Comment by laetitialalla** [comment]
Also, would it be possible to publish the train/val/test repartition of the 65 scenes id ? :) 

I modified the "properties"/"split" attribute in the meta.json files of some scenes to try out my network on a small dataset first. But now that I want to train the network on the whole dataset, I do not know where to find the original information without re-downloading everything from Zenodo ^^

Thanks a lot !

**Comment by MWieland** [comment]
Dear Laetitia,

Thank you for pointing us to this. I can confirm that both scenes exist locally, but have not been uploaded correctly to the remote data repository on Zenodo. We will upload the corresponding scenes and release a new dataset version within the next days. Will leave this issue open until then. 

Cheers,
Marc

**Comment by MWieland** [comment]
Ok, that was smoother than expected - the new dataset version (v1.0.1) is now online on Zenodo: https://zenodo.org/records/11278238
The Sentinel-1 scenes for samples #31 and #59 are in part2.zip and part4.zip respectively. Hope this helps.
